/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package glusterfsio;

public class glfs_java {
  public static int glfs_java_volume_size(long glfs, String path) {
    return glfs_javaJNI.glfs_java_volume_size(glfs, path);
  }

  public static int glfs_java_volume_free(long glfs, String path) {
    return glfs_javaJNI.glfs_java_volume_free(glfs, path);
  }

  public static String glfs_java_getxattr(long glfs, String path, String name) {
    return glfs_javaJNI.glfs_java_getxattr(glfs, path, name);
  }

  public static int glfs_java_chown(long glfs, String path, long uid, long gid) {
    return glfs_javaJNI.glfs_java_chown(glfs, path, uid, gid);
  }

  public static int glfs_java_chmod(long glfs, String path, long mode) {
    return glfs_javaJNI.glfs_java_chmod(glfs, path, mode);
  }

  public static long glfs_java_getmod(long glfs, String path) {
    return glfs_javaJNI.glfs_java_getmod(glfs, path);
  }

  public static long glfs_java_getuid(long glfs, String path) {
    return glfs_javaJNI.glfs_java_getuid(glfs, path);
  }

  public static long glfs_java_getgid(long glfs, String path) {
    return glfs_javaJNI.glfs_java_getgid(glfs, path);
  }

  public static int glfs_java_getblocksize(long glfs, String path) {
    return glfs_javaJNI.glfs_java_getblocksize(glfs, path);
  }

  public static int glfs_java_getmtime(long glfs, String path) {
    return glfs_javaJNI.glfs_java_getmtime(glfs, path);
  }

  public static int glfs_java_getctime(long glfs, String path) {
    return glfs_javaJNI.glfs_java_getctime(glfs, path);
  }

  public static int glfs_java_getatime(long glfs, String path) {
    return glfs_javaJNI.glfs_java_getatime(glfs, path);
  }

  public static long glfs_new(String volname) {
    return glfs_javaJNI.glfs_new(volname);
  }

  public static int glfs_init(long fs) {
    return glfs_javaJNI.glfs_init(fs);
  }

  public static int glfs_fini(long fs) {
    return glfs_javaJNI.glfs_fini(fs);
  }

  public static int glfs_set_logging(long fs, String logfile, int loglevel) {
    return glfs_javaJNI.glfs_set_logging(fs, logfile, loglevel);
  }

  public static int glfs_set_volfile_server(long fs, String transport, String host, int port) {
    return glfs_javaJNI.glfs_set_volfile_server(fs, transport, host, port);
  }

  public static int glfs_set_volfile(long fs, String volfile) {
    return glfs_javaJNI.glfs_set_volfile(fs, volfile);
  }

  public static int glfs_java_file_length(long fs, String path) {
    return glfs_javaJNI.glfs_java_file_length(fs, path);
  }

  public static boolean glfs_java_file_exists(long fs, String path) {
    return glfs_javaJNI.glfs_java_file_exists(fs, path);
  }

  public static boolean glfs_java_file_delete(long fs, String path) {
    return glfs_javaJNI.glfs_java_file_delete(fs, path);
  }

  public static boolean glfs_java_file_renameTo(long glfs, String src, String dst) {
    return glfs_javaJNI.glfs_java_file_renameTo(glfs, src, dst);
  }

  public static boolean glfs_java_file_createNewFile(long fs, String path) {
    return glfs_javaJNI.glfs_java_file_createNewFile(fs, path);
  }

  public static boolean glfs_java_file_mkdir(long fs, String path) {
    return glfs_javaJNI.glfs_java_file_mkdir(fs, path);
  }

  public static boolean glfs_java_file_isDirectory(long fs, String path) {
    return glfs_javaJNI.glfs_java_file_isDirectory(fs, path);
  }

  public static boolean glfs_java_file_isFile(long fs, String path) {
    return glfs_javaJNI.glfs_java_file_isFile(fs, path);
  }

  public static String[] glfs_java_list_dir(long fs, String path) {
    return glfs_javaJNI.glfs_java_list_dir(fs, path);
}

  public static long glfs_java_open_read(long fs, String filename) {
    return glfs_javaJNI.glfs_java_open_read(fs, filename);
  }

  public static long glfs_java_open_write(long fs, String filename) {
    return glfs_javaJNI.glfs_java_open_write(fs, filename);
  }

  public static int glfs_java_seek_set(long glfd, long location) {
    return glfs_javaJNI.glfs_java_seek_set(glfd, location);
  }

  public static int glfs_java_seek_current(long glfd, long location) {
    return glfs_javaJNI.glfs_java_seek_current(glfd, location);
  }

  public static int glfs_java_seek_end(long glfd, int location) {
    return glfs_javaJNI.glfs_java_seek_end(glfd, location);
  }

  public static int glfs_java_read(long fd,  byte[]  io_data, long size) {
    return glfs_javaJNI.glfs_java_read(fd, io_data, size);
  }

  public static int glfs_java_pread(long fd,  byte[]  io_data, long size, long offset) {
    return glfs_javaJNI.glfs_java_pread(fd, io_data, size, offset);
  }

  public static int glfs_java_write(long fd,  byte[]  io_data, long size) {
    return glfs_javaJNI.glfs_java_write(fd, io_data, size);
  }

  public static int glfs_java_pwrite(long fd,  byte[]  io_data, long size, long offset) {
    return glfs_javaJNI.glfs_java_pwrite(fd, io_data, size, offset);
  }

  public static int glfs_java_close(long fd) {
    return glfs_javaJNI.glfs_java_close(fd);
  }

}
